import textwrap
import json
import hashlib
from pathlib import Path
from typing import List, Dict, Any, Optional

class EdgeGenerator:
    """
    The 'Compiler' of the Trading Machine.
    Converts abstract Genomes (Logic Configurations) into concrete Python source code.
    
    Features:
    - Compiles genes to Python code.
    - Prevents duplicates via Genome Hashing.
    - Supports Technical, Fundamental, Regime, Cross-Sectional Ranking, and Direction (Long/Short).
    """
    
    def __init__(self, output_dir: str = "engines/engine_a_alpha/edges", registry_path: str = "data/governor/genome_registry.json"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.registry_path = Path(registry_path)
        self._load_registry()

    def _load_registry(self):
        if self.registry_path.exists():
            try:
                with open(self.registry_path, "r") as f:
                    self.registry = json.load(f)
            except Exception:
                self.registry = {}
        else:
            self.registry = {}

    def _save_registry(self):
        self.registry_path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.registry_path, "w") as f:
            json.dump(self.registry, f, indent=4)

    def _compute_genome_hash(self, genes: List[Dict[str, Any]], direction: str) -> str:
        # Sort genes by a stable key repr
        sorted_genes = sorted(genes, key=lambda g: json.dumps(g, sort_keys=True))
        gene_str = json.dumps(sorted_genes, sort_keys=True) + f"|{direction}"
        return hashlib.sha256(gene_str.encode("utf-8")).hexdigest()

    def generate_edge_code(self, edge_id: str, genes: List[Dict[str, Any]], direction: str = "long") -> str:
        class_name = self._to_class_name(edge_id)
        
        # 1. Imports
        code = f'''import pandas as pd
import numpy as np
from engines.engine_a_alpha.edge_base import EdgeBase
from engines.engine_a_alpha.edge_template import EdgeTemplate
from engines.data_manager.data_manager import DataManager

class {class_name}(EdgeBase, EdgeTemplate):
    """
    AUTOGENERATED EDGE: {edge_id}
    Origin: Genetic Evolution
    Genes: {genes}
    Direction: {direction}
    """
    
    EDGE_ID = "{edge_id}"
    EDGE_GROUP = "evolutionary"
    EDGE_CATEGORY = "compiled_composite"

    def __init__(self, params=None):
        super().__init__()
        self.set_params(params)
        self.direction = self.params.get("direction", "{direction}")
        self.dm = DataManager()
        self.fundamental_cache = {{}}
        # Internal Regime Detector
        from engines.engine_d_research.regime_detector import RegimeDetector
        self.regime_detector = RegimeDetector()
        self.regime_cache = {{}}

    def compute_signals(self, data_map, as_of):
        scores = {{}}
        
        # 1. Detect Regime (Context)
        spy_df = data_map.get("SPY")
        current_regime = {{"trend": "unknown", "volatility": "unknown"}}
        if spy_df is not None:
            spy_last = spy_df.index[-1]
            if spy_last in self.regime_cache:
                current_regime = self.regime_cache[spy_last]
            else:
                slice_spy = spy_df.loc[:as_of]
                if not slice_spy.empty:
                    current_regime = self.regime_detector.detect_regime(slice_spy)
                    self.regime_cache[spy_last] = current_regime
                    self.regime_cache["spy_df_ref"] = slice_spy

        # 2. Calculation Phase
        ticker_gene_vals = {{}}
        gene_all_vals = {{i: [] for i in range({len(genes)})}}

        for t, df in data_map.items():
            if len(df) < 50 or "Close" not in df:
                continue
            
            ticker_gene_vals[t] = {{}}
'''     
        # Calculation Loops
        for i, gene in enumerate(genes):
            g_type = gene.get("type", "technical")
            
            # Regime genes can be pre-calculated
            if g_type == "regime":
                target = gene.get("is")
                code += f'''
            # Gene {i} (Regime)
            trend = current_regime.get("trend", "unknown")
            vol = current_regime.get("volatility", "unknown")
            # If not matching target, store False
            match = "{target}" in [trend, vol]
            ticker_gene_vals[t][{i}] = match
'''
                continue

            # Technical / Fundamental Calc
            val_block = ""
            if g_type == "technical":
                ind = gene.get("indicator")
                win = gene.get("window", 14)
                
                if ind == "rsi":
                    val_block = f'''
            delta = df["Close"].diff()
            up, down = delta.clip(lower=0), -delta.clip(upper=0)
            rs = up.rolling({win}).mean() / (down.rolling({win}).mean() + 1e-9)
            rsi = 100 - (100 / (1 + rs))
            val_{i} = float(rsi.iloc[-1])'''
                elif ind == "volatility":
                    val_block = f'''
            val_{i} = float(df["Close"].pct_change().rolling({win}).std().iloc[-1])'''
                elif ind == "sma_dist_pct":
                    val_block = f'''
            sma = df["Close"].rolling({win}).mean().iloc[-1]
            price = df["Close"].iloc[-1]
            val_{i} = (price - sma) / (sma + 1e-9)'''
                elif ind == "donchian_breakout":
                    val_block = f'''
            highs = df["High"]
            roll_max = highs.rolling({win}).max().shift(1).iloc[-1]
            curr_close = df["Close"].iloc[-1]
            val_{i} = (curr_close - roll_max) / (roll_max + 1e-9)'''
                elif ind == "pivot_position":
                    val_block = f'''
            if len(df) >= 2:
                prev = df.iloc[-2]
                pivot = (prev["High"] + prev["Low"] + prev["Close"]) / 3
                curr = df["Close"].iloc[-1]
                val_{i} = (curr - pivot) / (pivot + 1e-9)
            else:
                val_{i} = None'''
                elif ind == "momentum_roc":
                    val_block = f'''
            if len(df) > {win}:
                curr = df["Close"].iloc[-1]
                past = df["Close"].iloc[-1 - {win}]
                val_{i} = (curr / past) - 1.0
            else:
                val_{i} = None'''
                elif ind == "sma_cross":
                    fast_win = gene.get("window_fast", 10)
                    slow_win = gene.get("window_slow", 50)
                    val_block = f'''
            fast_ma = df["Close"].rolling({fast_win}).mean().iloc[-1]
            slow_ma = df["Close"].rolling({slow_win}).mean().iloc[-1]
            val_{i} = 1.0 if fast_ma > slow_ma else -1.0'''
                elif ind == "volatility_diff":
                    val_block = f'''
            curr_vol = df["Close"].pct_change().tail(10).std()
            past_vol = df["Close"].pct_change().shift(10).tail(10).std()
            val_{i} = float(curr_vol - past_vol)'''
                elif ind == "residual_momentum":
                    val_block = f'''
            spy_df_ref = self.regime_cache.get("spy_df_ref")
            if spy_df_ref is not None and len(df) > {win}:
                stock_rets = df["Close"].pct_change().dropna().tail({win})
                spy_rets = spy_df_ref["Close"].pct_change().dropna().reindex(stock_rets.index)
                if len(stock_rets) == len(spy_rets) and len(stock_rets) > 10:
                    cov = np.cov(stock_rets, spy_rets)[0][1]
                    var_m = np.var(spy_rets) + 1e-9
                    beta = cov / var_m
                    stock_cum = (1 + stock_rets).prod() - 1
                    spy_cum = (1 + spy_rets).prod() - 1
                    val_{i} = float(stock_cum - (beta * spy_cum))
                else:
                    val_{i} = None
            else:
                val_{i} = None'''

            elif g_type == "fundamental":
                metric = gene.get("metric")
                val_block = f'''
            if t not in self.fundamental_cache:
                 self.fundamental_cache[t] = self.dm.fetch_historical_fundamentals(t)
            fund_df = self.fundamental_cache[t]
            val_{i} = None
            if not fund_df.empty and "{metric}" in fund_df.columns:
                try:
                    idx_loc = fund_df.index.get_indexer([as_of], method='pad')[0]
                    if idx_loc != -1:
                        val_{i} = fund_df.iloc[idx_loc]["{metric}"]
                except:
                    pass'''

            code += f"\n            # Gene {i} ({g_type})" + val_block
            code += f'''
            if val_{i} is not None:
                ticker_gene_vals[t][{i}] = val_{i}
                if isinstance(val_{i}, (int, float)):
                    gene_all_vals[{i}].append(val_{i})
'''

        # 3. Evaluation Phase
        code += '''
        # 3. Evaluation Phase
        for t in ticker_gene_vals:
            conditions_met = True
'''
        for i, gene in enumerate(genes):
            op = gene.get("operator", "<")
            thresh = gene.get("threshold", 0.0)
            
            code += f'''
            # Check Gene {i}
            val = ticker_gene_vals[t].get({i})
            if val is None:
                conditions_met = False
            else:'''
            
            if gene.get("type") == "regime":
                if op == "is_not":
                    code += f'''
                if val: conditions_met = False # Expecting False
'''
                else:
                    code += f'''
                if not val: conditions_met = False # Expecting True
'''
            elif op == "top_percentile":
                code += f'''
                cutoff = np.percentile(gene_all_vals[{i}], {thresh})
                if val < cutoff: conditions_met = False
'''
            elif op == "bottom_percentile":
                code += f'''
                cutoff = np.percentile(gene_all_vals[{i}], {thresh})
                if val > cutoff: conditions_met = False
'''
            elif op == "less":
                code += f'''
                if not (val < {thresh}): conditions_met = False
'''
            elif op == "greater":
                code += f'''
                if not (val > {thresh}): conditions_met = False
'''

        # Final Score Logic with Direction
        code += '''
            if conditions_met:
                scores[t] = 1.0 if self.direction == "long" else -1.0
            else:
                scores[t] = 0.0
                
        return scores
'''
        return code

    def save_edge(self, edge_id: str, genes: List[Dict[str, Any]], direction: str = "long") -> str:
        # 1. Compute Hash
        genome_hash = self._compute_genome_hash(genes, direction)
        
        # 2. Check Deduplication
        if genome_hash in self.registry:
            existing_id = self.registry[genome_hash]["edge_id"]
            existing_path = self.output_dir / f"{existing_id}.py"
            
            if existing_path.exists():
                print(f"[EDGE_GENERATOR] DUPLICATE DETECTED. Genes match {existing_id}. Reusing existing edge.")
                return str(existing_path)
            else:
                print(f"[EDGE_GENERATOR] Registry mismatch for {existing_id}. Recreating file.")
        
        # 3. Generate Code
        code = self.generate_edge_code(edge_id, genes, direction)
        filename = f"{edge_id}.py"
        path = self.output_dir / filename
        
        with open(path, "w") as f:
            f.write(code)
            
        # 4. Update Registry
        self.registry[genome_hash] = {
            "edge_id": edge_id,
            "genes": genes,
            "direction": direction,
            "path": str(path)
        }
        self._save_registry()
        
        print(f"[EDGE_GENERATOR] Compiled {edge_id} to {path} ({direction})")
        return str(path)

    def _to_class_name(self, edge_id: str) -> str:
        """snake_case to CamelCase"""
        return "".join(word.title() for word in edge_id.split("_"))

if __name__ == "__main__":
    # Test Compilation
    gen = EdgeGenerator(output_dir="engines/engine_a_alpha/edges")
    sample_genes = [
        {"type": "technical", "indicator": "momentum_roc", "window": 20, "operator": "greater", "threshold": 0.0}
    ]
    
    # Run Test: Long vs Short
    print("--- Testing Phase 3 Direction Compiler ---")
    gen.save_edge("autogen_phase3_long", sample_genes, direction="long")
    gen.save_edge("autogen_phase3_short", sample_genes, direction="short")
