import pandas as pd
import numpy as np
from engines.engine_a_alpha.edge_base import EdgeBase
from engines.engine_a_alpha.edge_template import EdgeTemplate
from engines.data_manager.data_manager import DataManager

class AutogenPhase3Long(EdgeBase, EdgeTemplate):
    """
    AUTOGENERATED EDGE: autogen_phase3_long
    Origin: Genetic Evolution
    Genes: [{'type': 'technical', 'indicator': 'momentum_roc', 'window': 20, 'operator': 'greater', 'threshold': 0.0}]
    Direction: long
    """
    
    EDGE_ID = "autogen_phase3_long"
    EDGE_GROUP = "evolutionary"
    EDGE_CATEGORY = "compiled_composite"

    def __init__(self, params=None):
        super().__init__()
        self.set_params(params)
        self.direction = self.params.get("direction", "long")
        self.dm = DataManager()
        self.fundamental_cache = {}
        # Internal Regime Detector
        from engines.engine_d_research.regime_detector import RegimeDetector
        self.regime_detector = RegimeDetector()
        self.regime_cache = {}

    def compute_signals(self, data_map, as_of):
        scores = {}
        
        # 1. Detect Regime (Context)
        spy_df = data_map.get("SPY")
        current_regime = {"trend": "unknown", "volatility": "unknown"}
        if spy_df is not None:
            spy_last = spy_df.index[-1]
            if spy_last in self.regime_cache:
                current_regime = self.regime_cache[spy_last]
            else:
                slice_spy = spy_df.loc[:as_of]
                if not slice_spy.empty:
                    current_regime = self.regime_detector.detect_regime(slice_spy)
                    self.regime_cache[spy_last] = current_regime
                    self.regime_cache["spy_df_ref"] = slice_spy

        # 2. Calculation Phase
        ticker_gene_vals = {}
        gene_all_vals = {i: [] for i in range(1)}

        for t, df in data_map.items():
            if len(df) < 50 or "Close" not in df:
                continue
            
            ticker_gene_vals[t] = {}

            # Gene 0 (technical)
            if len(df) > 20:
                curr = df["Close"].iloc[-1]
                past = df["Close"].iloc[-1 - 20]
                val_0 = (curr / past) - 1.0
            else:
                val_0 = None
            if val_0 is not None:
                ticker_gene_vals[t][0] = val_0
                if isinstance(val_0, (int, float)):
                    gene_all_vals[0].append(val_0)

        # 3. Evaluation Phase
        for t in ticker_gene_vals:
            conditions_met = True

            # Check Gene 0
            val = ticker_gene_vals[t].get(0)
            if val is None:
                conditions_met = False
            else:
                if not (val > 0.0): conditions_met = False

            if conditions_met:
                scores[t] = 1.0 if self.direction == "long" else -1.0
            else:
                scores[t] = 0.0
                
        return scores
