import pandas as pd
import numpy as np
from engines.engine_a_alpha.edge_base import EdgeBase
from engines.engine_a_alpha.edge_template import EdgeTemplate
from engines.data_manager.data_manager import DataManager

class AutogenPhase2ComplexTest(EdgeBase, EdgeTemplate):
    """
    AUTOGENERATED EDGE: autogen_phase2_complex_test
    Origin: Genetic Evolution
    Genes: [{'type': 'regime', 'is': 'bull'}, {'type': 'technical', 'indicator': 'residual_momentum', 'window': 20, 'operator': 'greater', 'threshold': 0.0}, {'type': 'technical', 'indicator': 'momentum_roc', 'window': 20, 'operator': 'top_percentile', 'threshold': 50}]
    """
    
    EDGE_ID = "autogen_phase2_complex_test"
    EDGE_GROUP = "evolutionary"
    EDGE_CATEGORY = "compiled_composite"

    def __init__(self, params=None):
        super().__init__()
        self.set_params(params)
        self.dm = DataManager()
        self.fundamental_cache = {}
    def compute_signals(self, data_map, as_of):
        scores = {}

        # 1. Regime context (provided by AlphaEngine via regime_meta attribute)
        current_regime = self.regime_meta or {"trend": "unknown", "volatility": "unknown"}

        # 2. Calculation Phase
        ticker_gene_vals = {}
        gene_all_vals = {i: [] for i in range(3)}

        for t, df in data_map.items():
            if len(df) < 50 or "Close" not in df:
                continue
            
            ticker_gene_vals[t] = {}

            # Gene 0 (Regime)
            trend = current_regime.get("trend", "unknown")
            vol = current_regime.get("volatility", "unknown")
            if "bull" in [trend, vol]:
                ticker_gene_vals[t][0] = True
            else:
                ticker_gene_vals[t][0] = False

            # Gene 1 (technical)
            spy_df_ref = self.regime_cache.get("spy_df_ref")
            if spy_df_ref is not None and len(df) > 20:
                stock_rets = df["Close"].pct_change().dropna().tail(20)
                spy_rets = spy_df_ref["Close"].pct_change().dropna().reindex(stock_rets.index)
                if len(stock_rets) == len(spy_rets) and len(stock_rets) > 10:
                    cov = np.cov(stock_rets, spy_rets)[0][1]
                    var_m = np.var(spy_rets) + 1e-9
                    beta = cov / var_m
                    stock_cum = (1 + stock_rets).prod() - 1
                    spy_cum = (1 + spy_rets).prod() - 1
                    val_1 = float(stock_cum - (beta * spy_cum))
                else:
                    val_1 = None
            else:
                val_1 = None
            if val_1 is not None:
                ticker_gene_vals[t][1] = val_1
                if isinstance(val_1, (int, float)):
                    gene_all_vals[1].append(val_1)

            # Gene 2 (technical)
            if len(df) > 20:
                curr = df["Close"].iloc[-1]
                past = df["Close"].iloc[-1 - 20]
                val_2 = (curr / past) - 1.0
            else:
                val_2 = None
            if val_2 is not None:
                ticker_gene_vals[t][2] = val_2
                if isinstance(val_2, (int, float)):
                    gene_all_vals[2].append(val_2)

        # 3. Evaluation Phase
        for t in ticker_gene_vals:
            conditions_met = True

            # Check Gene 0
            val = ticker_gene_vals[t].get(0)
            if val is None:
                conditions_met = False
            else:
                if not val: conditions_met = False # Expecting True

            # Check Gene 1
            val = ticker_gene_vals[t].get(1)
            if val is None:
                conditions_met = False
            else:
                if not (val > 0.0): conditions_met = False

            # Check Gene 2
            val = ticker_gene_vals[t].get(2)
            if val is None:
                conditions_met = False
            else:
                cutoff = np.percentile(gene_all_vals[2], 50)
                if val < cutoff: conditions_met = False

            if conditions_met:
                scores[t] = 1.0
            else:
                scores[t] = 0.0
                
        return scores
