import pandas as pd
import numpy as np
from engines.engine_a_alpha.edge_base import EdgeBase
from engines.engine_a_alpha.edge_template import EdgeTemplate
from engines.data_manager.data_manager import DataManager

class AutogenPhase2RankTest(EdgeBase, EdgeTemplate):
    """
    AUTOGENERATED EDGE: autogen_phase2_rank_test
    Origin: Genetic Evolution
    Genes: [{'type': 'regime', 'is': 'bull'}, {'type': 'technical', 'indicator': 'rsi', 'window': 14, 'operator': 'top_percentile', 'threshold': 80}]
    """
    
    EDGE_ID = "autogen_phase2_rank_test"
    EDGE_GROUP = "evolutionary"
    EDGE_CATEGORY = "compiled_composite"

    def __init__(self, params=None):
        super().__init__()
        self.set_params(params)
        self.dm = DataManager()
        self.fundamental_cache = {}
    def compute_signals(self, data_map, as_of):
        scores = {}

        # 1. Regime context (provided by AlphaEngine via regime_meta attribute)
        current_regime = self.regime_meta or {"trend": "unknown", "volatility": "unknown"}

        # 2. Calculation Phase
        ticker_gene_vals = {}
        gene_all_vals = {i: [] for i in range(2)}

        for t, df in data_map.items():
            if len(df) < 50 or "Close" not in df:
                continue
            
            ticker_gene_vals[t] = {}

            # Gene 0 (Regime)
            trend = current_regime.get("trend", "unknown")
            vol = current_regime.get("volatility", "unknown")
            if "bull" in [trend, vol]:
                ticker_gene_vals[t][0] = True
            else:
                ticker_gene_vals[t][0] = False

            # Gene 1 (technical)
            delta = df["Close"].diff()
            up, down = delta.clip(lower=0), -delta.clip(upper=0)
            rs = up.rolling(14).mean() / (down.rolling(14).mean() + 1e-9)
            rsi = 100 - (100 / (1 + rs))
            val_1 = float(rsi.iloc[-1])
            if val_1 is not None:
                ticker_gene_vals[t][1] = val_1
                if isinstance(val_1, (int, float)):
                    gene_all_vals[1].append(val_1)

        # 3. Evaluation Phase
        for t in ticker_gene_vals:
            conditions_met = True

            # Check Gene 0
            val = ticker_gene_vals[t].get(0)
            if val is None:
                conditions_met = False
            else:
                if not val: conditions_met = False # Expecting True

            # Check Gene 1
            val = ticker_gene_vals[t].get(1)
            if val is None:
                conditions_met = False
            else:
                cutoff = np.percentile(gene_all_vals[1], 80)
                if val < cutoff: conditions_met = False

            if conditions_met:
                scores[t] = 1.0
            else:
                scores[t] = 0.0
                
        return scores
