
import pandas as pd
import numpy as np
from engines.engine_a_alpha.edge_base import EdgeBase
from engines.engine_a_alpha.edge_template import EdgeTemplate
from engines.data_manager.data_manager import DataManager

class AutogenValueRsi(EdgeBase, EdgeTemplate):
    """
    AUTOGENERATED EDGE: autogen_value_rsi
    Origin: Genetic Evolution
    Genes: [{'type': 'technical', 'indicator': 'rsi', 'window': 14, 'operator': 'less', 'threshold': 30}, {'type': 'fundamental', 'metric': 'PE_Ratio', 'operator': 'less', 'threshold': 15}]
    """
    
    EDGE_ID = "autogen_value_rsi"
    EDGE_GROUP = "evolutionary"
    EDGE_CATEGORY = "compiled_composite"

    def __init__(self, params=None):
        super().__init__()
        self.set_params(params)
        self.dm = DataManager()
        self.fundamental_cache = {} 

    def compute_signals(self, data_map, as_of):
        scores = {}
        
        for t, df in data_map.items():
            if len(df) < 200 or "Close" not in df:
                continue

            # --- Logic Block ---
            conditions_met = True

            # Gene 1: technical rsi less 30
            
            # RSI Calculation
            delta = df["Close"].diff()
            up, down = delta.clip(lower=0), -delta.clip(upper=0)
            rs = up.rolling(14).mean() / (down.rolling(14).mean() + 1e-9)
            rsi = 100 - (100 / (1 + rs))
            val_0 = float(rsi.iloc[-1])

            if val_0 is None or not (val_0 < 30):
                conditions_met = False
            # Gene 2: fundamental PE_Ratio less 15

            # Fundamental Lookup
            if t not in self.fundamental_cache:
                 self.fundamental_cache[t] = self.dm.fetch_historical_fundamentals(t)
            fund_df = self.fundamental_cache[t]
            val_1 = None
            if not fund_df.empty and "PE_Ratio" in fund_df.columns:
                try:
                    idx_loc = fund_df.index.get_indexer([as_of], method='pad')[0]
                    if idx_loc != -1:
                        val_1 = fund_df.iloc[idx_loc]["PE_Ratio"]
                except:
                    pass

            if val_1 is None or not (val_1 < 15):
                conditions_met = False

            if conditions_met:
                scores[t] = 1.0
            else:
                scores[t] = 0.0
                
        return scores
